name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_USER: roar
          POSTGRES_PASSWORD: password
          POSTGRES_DB: roar_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:6.0-alpine
        ports:
          - 6379:6379

    steps:
      - name: Set branch name
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run lint
      - run: cp .example.env .env.test
      - run: NODE_ENV=test npm run knex migrate:latest
      - run: npm test

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,ref,author,took
        if: always()
        env:
          CI: true
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ENGINEERING_CHANNEL_WEBHOOK_URL }}
